export const state = {
  conversations: [],
  currentConversationId: null,
  currentMessages: [],
  copilotLoading: false,
  plans: [],
  currentPlanId: null,
  currentPlanDetail: null,
  copilotPlanId: '',
  copilotUseUnifiedContext: false,
  copilotIncludeResearchContext: false,
  copilotIncludeProjectionContext: false,
  copilotResearchSymbols: '',
  copilotContextSummary: '',
  copilotContextPayload: null,
  copilotContextLoading: false,
  copilotContextUpdatedAt: null,
  workflowTemplates: [],
  todayDashboard: null,
  financialProfile: null,
  onboardingStatus: null,
  recommendations: [],
  recommendationFilterStatus: 'proposed',
  recommendationFilterPlanId: '',
  recommendationSort: 'ranked',
  recommendationEditingId: null,
  recommendationPreview: null,
  recommendationClosureAnalytics: null,
  planClosureSummary: null,
  planClosureTrend: null,
  dashboardClosureTrend: null,
  researchCompare: null,
  researchDossier: null,
};

export const PLAN_SETTING_FIELDS = [
  { key: 'annual_contribution_usd', inputId: 'setting-annual-contribution', label: 'Annual Contribution (USD)', scale: 1, integer: false, step: 100, min: 0, placeholder: 'e.g. 22000' },
  { key: 'years', inputId: 'setting-years', label: 'Horizon (Years)', scale: 1, integer: true, step: 1, min: 1, max: 80, placeholder: 'e.g. 25' },
  { key: 'hsa_extra_contribution_usd', inputId: 'setting-hsa-extra', label: 'HSA Extra (USD)', scale: 1, integer: false, step: 100, min: 0, placeholder: 'e.g. 1000' },
  { key: 'marginal_tax_rate', inputId: 'setting-marginal-tax-rate', label: 'Tax Rate (%)', scale: 100, integer: false, step: 0.01, min: 0, max: 100, placeholder: 'e.g. 24' },
  { key: 'state_tax_rate', inputId: 'setting-state-tax-rate', label: 'State Tax Rate (%)', scale: 100, integer: false, step: 0.01, min: 0, max: 100, placeholder: 'e.g. 5' },
  { key: 'simulation_historical_start_year', inputId: 'setting-simulation-historical-start-year', label: 'Historical Start Year', scale: 1, integer: true, step: 1, min: 1928, max: 2024, placeholder: 'e.g. 1980' },
  { key: 'simulation_seed', inputId: 'setting-simulation-seed', label: 'Simulation Seed', scale: 1, integer: true, step: 1, min: 0, max: 2147483647, placeholder: 'e.g. 9521' },
  { key: 'household_partner_income_usd', inputId: 'setting-household-partner-income', label: 'Partner Income Annual (USD)', scale: 1, integer: false, step: 100, min: 0, placeholder: 'e.g. 90000' },
  { key: 'household_partner_income_growth_rate', inputId: 'setting-household-partner-income-growth-rate', label: 'Partner Income Growth (%)', scale: 100, integer: false, step: 0.01, min: -100, max: 100, placeholder: 'e.g. 3' },
  { key: 'household_partner_retirement_age', inputId: 'setting-household-partner-retirement-age', label: 'Partner Retirement Age', scale: 1, integer: true, step: 1, min: 0, max: 120, placeholder: 'e.g. 65' },
  { key: 'household_partner_social_security_annual_usd', inputId: 'setting-household-partner-social-security-annual', label: 'Partner Social Security Annual (USD)', scale: 1, integer: false, step: 100, min: 0, placeholder: 'e.g. 24000' },
  { key: 'household_partner_social_security_claiming_age', inputId: 'setting-household-partner-social-security-claiming-age', label: 'Partner Social Security Claim Age', scale: 1, integer: true, step: 1, min: 0, max: 120, placeholder: 'e.g. 67' },
  { key: 'household_shared_goal_target_usd', inputId: 'setting-household-shared-goal-target', label: 'Shared Goal Target (USD)', scale: 1, integer: false, step: 100, min: 0, placeholder: 'e.g. 150000' },
  { key: 'household_shared_goal_target_year', inputId: 'setting-household-shared-goal-target-year', label: 'Shared Goal Target Year', scale: 1, integer: true, step: 1, min: 1900, max: 2500, placeholder: 'e.g. 2035' },
  { key: 'roth_conversion_annual_amount_usd', inputId: 'setting-roth-conversion-annual', label: 'Roth Conversion Annual (USD)', scale: 1, integer: false, step: 100, min: 0, placeholder: 'e.g. 12000' },
  { key: 'roth_conversion_start_age', inputId: 'setting-roth-conversion-start-age', label: 'Roth Conversion Start Age', scale: 1, integer: true, step: 1, min: 0, max: 120, placeholder: 'e.g. 60' },
  { key: 'roth_conversion_end_age', inputId: 'setting-roth-conversion-end-age', label: 'Roth Conversion End Age', scale: 1, integer: true, step: 1, min: 0, max: 120, placeholder: 'e.g. 73' },
  { key: 'inflation_rate', inputId: 'setting-inflation-rate', label: 'Inflation Rate (%)', scale: 100, integer: false, step: 0.01, min: -100, max: 100, placeholder: 'e.g. 3' },
  { key: 'expected_return_baseline', inputId: 'setting-return-baseline', label: 'Baseline Return (%)', scale: 100, integer: false, step: 0.01, min: -95, max: 100, placeholder: 'e.g. 7' },
  { key: 'expected_return_optimistic', inputId: 'setting-return-optimistic', label: 'Optimistic Return (%)', scale: 100, integer: false, step: 0.01, min: -95, max: 100, placeholder: 'e.g. 9' },
  { key: 'expected_return_conservative', inputId: 'setting-return-conservative', label: 'Conservative Return (%)', scale: 100, integer: false, step: 0.01, min: -95, max: 100, placeholder: 'e.g. 5' },
];

export const DIFF_SETTING_FIELDS = PLAN_SETTING_FIELDS.map(f => ({
  ...f,
  inputId: f.inputId.replace('setting-', 'diff-'),
  placeholder: 'Optional',
}));
